VALID_CASES = [
    {
        "description": "Normal high-activity profile",
        "payload": {
            "user_id": "USR-1001",
            "interaction_count": 500.0,
            "average_rating": 4.5,
            "rating_std": 0.5,
            "activity_span_days": 300.0,
            "recency_days": 2.0,
            "active_days": 100.0,
            "interactions_per_active_day": 5.0,
            "weekend_interaction_ratio": 0.3,
            "unique_genre_count": 15,
            "genre_prop_action": 0.0,
            "genre_prop_adventure": 0.0,
            "genre_prop_animation": 0.0,
            "genre_prop_childrens": 0.0,
            "genre_prop_comedy": 0.5,
            "genre_prop_crime": 0.0,
            "genre_prop_documentary": 0.0,
            "genre_prop_drama": 0.5,
            "genre_prop_fantasy": 0.0,
            "genre_prop_film_noir": 0.0,
            "genre_prop_horror": 0.0,
            "genre_prop_musical": 0.0,
            "genre_prop_mystery": 0.0,
            "genre_prop_romance": 0.0,
            "genre_prop_sci_fi": 0.0,
            "genre_prop_thriller": 0.0,
            "genre_prop_war": 0.0,
            "genre_prop_western": 0.0
        },
        "expected_status": 200
    },
    {
        "description": "Normal casual profile",
        "payload": {
            "user_id": "USR-1002",
            "interaction_count": 25.0,
            "average_rating": 3.0,
            "rating_std": 1.2,
            "activity_span_days": 10.0,
            "recency_days": 50.0,
            "active_days": 5.0,
            "interactions_per_active_day": 5.0,
            "weekend_interaction_ratio": 0.8,
            "unique_genre_count": 2,
            "genre_prop_action": 0.8,
            "genre_prop_adventure": 0.0,
            "genre_prop_animation": 0.0,
            "genre_prop_childrens": 0.0,
            "genre_prop_comedy": 0.2,
            "genre_prop_crime": 0.0,
            "genre_prop_documentary": 0.0,
            "genre_prop_drama": 0.0,
            "genre_prop_fantasy": 0.0,
            "genre_prop_film_noir": 0.0,
            "genre_prop_horror": 0.0,
            "genre_prop_musical": 0.0,
            "genre_prop_mystery": 0.0,
            "genre_prop_romance": 0.0,
            "genre_prop_sci_fi": 0.0,
            "genre_prop_thriller": 0.0,
            "genre_prop_war": 0.0,
            "genre_prop_western": 0.0
        },
        "expected_status": 200
    }
]

INVALID_CASES = [
    {
        "description": "Missing required field (user_id)",
        "payload": {
            "interaction_count": 500.0,
            "average_rating": 4.5,
            "rating_std": 0.5,
            "activity_span_days": 300.0,
            "recency_days": 2.0,
            "active_days": 100.0,
            "interactions_per_active_day": 5.0,
            "weekend_interaction_ratio": 0.3,
            "unique_genre_count": 15,
            "genre_prop_action": 0.0,
            "genre_prop_adventure": 0.0,
            "genre_prop_animation": 0.0,
            "genre_prop_childrens": 0.0,
            "genre_prop_comedy": 0.5,
            "genre_prop_crime": 0.0,
            "genre_prop_documentary": 0.0,
            "genre_prop_drama": 0.5,
            "genre_prop_fantasy": 0.0,
            "genre_prop_film_noir": 0.0,
            "genre_prop_horror": 0.0,
            "genre_prop_musical": 0.0,
            "genre_prop_mystery": 0.0,
            "genre_prop_romance": 0.0,
            "genre_prop_sci_fi": 0.0,
            "genre_prop_thriller": 0.0,
            "genre_prop_war": 0.0,
            "genre_prop_western": 0.0
        },
        "expected_status": 422
    },
    {
        "description": "Negative interaction_count",
        "payload": {
            "user_id": "USR-1002",
            "interaction_count": -25.0,
            "average_rating": 3.0,
            "rating_std": 1.2,
            "activity_span_days": 10.0,
            "recency_days": 50.0,
            "active_days": 5.0,
            "interactions_per_active_day": 5.0,
            "weekend_interaction_ratio": 0.8,
            "unique_genre_count": 2,
            "genre_prop_action": 0.8,
            "genre_prop_adventure": 0.0,
            "genre_prop_animation": 0.0,
            "genre_prop_childrens": 0.0,
            "genre_prop_comedy": 0.2,
            "genre_prop_crime": 0.0,
            "genre_prop_documentary": 0.0,
            "genre_prop_drama": 0.0,
            "genre_prop_fantasy": 0.0,
            "genre_prop_film_noir": 0.0,
            "genre_prop_horror": 0.0,
            "genre_prop_musical": 0.0,
            "genre_prop_mystery": 0.0,
            "genre_prop_romance": 0.0,
            "genre_prop_sci_fi": 0.0,
            "genre_prop_thriller": 0.0,
            "genre_prop_war": 0.0,
            "genre_prop_western": 0.0
        },
        "expected_status": 422
    },
    {
        "description": "Wrong numeric data type (string instead of float)",
        "payload": {
            "user_id": "USR-1002",
            "interaction_count": "ten",
            "average_rating": 3.0,
            "rating_std": 1.2,
            "activity_span_days": 10.0,
            "recency_days": 50.0,
            "active_days": 5.0,
            "interactions_per_active_day": 5.0,
            "weekend_interaction_ratio": 0.8,
            "unique_genre_count": 2,
            "genre_prop_action": 0.8,
            "genre_prop_adventure": 0.0,
            "genre_prop_animation": 0.0,
            "genre_prop_childrens": 0.0,
            "genre_prop_comedy": 0.2,
            "genre_prop_crime": 0.0,
            "genre_prop_documentary": 0.0,
            "genre_prop_drama": 0.0,
            "genre_prop_fantasy": 0.0,
            "genre_prop_film_noir": 0.0,
            "genre_prop_horror": 0.0,
            "genre_prop_musical": 0.0,
            "genre_prop_mystery": 0.0,
            "genre_prop_romance": 0.0,
            "genre_prop_sci_fi": 0.0,
            "genre_prop_thriller": 0.0,
            "genre_prop_war": 0.0,
            "genre_prop_western": 0.0
        },
        "expected_status": 422
    },
    {
        "description": "Rating out of bounds",
        "payload": {
            "user_id": "USR-1002",
            "interaction_count": 25.0,
            "average_rating": 6.5,
            "rating_std": 1.2,
            "activity_span_days": 10.0,
            "recency_days": 50.0,
            "active_days": 5.0,
            "interactions_per_active_day": 5.0,
            "weekend_interaction_ratio": 0.8,
            "unique_genre_count": 2,
            "genre_prop_action": 0.8,
            "genre_prop_adventure": 0.0,
            "genre_prop_animation": 0.0,
            "genre_prop_childrens": 0.0,
            "genre_prop_comedy": 0.2,
            "genre_prop_crime": 0.0,
            "genre_prop_documentary": 0.0,
            "genre_prop_drama": 0.0,
            "genre_prop_fantasy": 0.0,
            "genre_prop_film_noir": 0.0,
            "genre_prop_horror": 0.0,
            "genre_prop_musical": 0.0,
            "genre_prop_mystery": 0.0,
            "genre_prop_romance": 0.0,
            "genre_prop_sci_fi": 0.0,
            "genre_prop_thriller": 0.0,
            "genre_prop_war": 0.0,
            "genre_prop_western": 0.0
        },
        "expected_status": 422
    }
]
